# Generated by Django 4.2.7 on 2026-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('classroom_type', models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('tutorial', 'Tutorial Room'), ('seminar', 'Seminar Room')], default='lecture', max_length=20)),
                ('virtual_meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
